#!/bin/bash

# confd
/usr/local/bin/confd -onetime -backend env || { echo 'confd failed' ; exit 1; }

set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- apache2-foreground "$@"
fi

exec "$@"
